### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by terrisgit** [keithf4/pg_doc_store#2]
My Postgres server is on Heroku and I can't add an extension. Adding these procs to a schema is working fine. This will allow me to upgrade the procs (install new procs into a new schema -- keep tables in different schema from procs) without affecting running code.

Just a note... after creating multiple tables, I gave up on that and put all docs in one table and added a type key in my documents. I have other requirements that make having multiple tables a pain.

**Comment by keithf4** [comment]
You should be able to install this, and any updates for it, by just running `make` locally to generate the single SQL file that extensions require then going back and replacing the @extschema@ macro with whatever schema you want to install the functions to.
The issue with installing unsupported extensions to things like Heroku & Amazon RDS is that you'll never know what version of the extension you're on, which makes installing updates challenging. You can do the same find-n-replace with @extschema@ in any extension updates, but you have to be sure which version you're on and you have to do them one at a time.

I haven't done much with document storage myself. What's the purpose of the type key?

**Comment by terrisgit** [comment]
The purpose of a type column is to allow multiple document types in a single table. I am still experimenting with that idea. There are probably issues with having giant tables/indexes in postgres.
